/**
* User service
* User service
*
* The version of the OpenAPI document: 1.0.0
* Contact: alxminyaev@gmail.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package dev.alxminyaev.feature.user.api.models

import dev.alxminyaev.feature.user.api.models.Profile

/**
 * 
 * @param id 
 * @param roles 
 * @param profile 
 */
data class UserResponse (
    val id: kotlin.Long,
    val roles: kotlin.Array<kotlin.Int>? = null,
    val profile: Profile? = null
) 

